//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INYTDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public System.Guid AuditLogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string EventType { get; set; }
        public string EntityName { get; set; }
        public string RecordId { get; set; }
        public string ColumnName { get; set; }
        public string OriginalValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
