//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INYTDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRegistration
    {
        public int Id { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerEmailAddress { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerMobileNumber { get; set; }
        public Nullable<bool> HasAgreedTC { get; set; }
    }
}
