//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INYTDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<int> MessageFromId { get; set; }
        public Nullable<int> MessageToId { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public string MessageBody { get; set; }
        public string MessageSubject { get; set; }
        public string MessageAttachment { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> isArchived { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
